global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'auth-app'
    static_configs:
      - targets: ['auth-app:$APP_PORT']
